site_name: Manexp Web Lists Documentation
site_author: Edouard Brülhart

repo_name: edouardbruelhart/Manexp-Web-Lists
copyright: Maintained by <a
  href="https://github.com/edouardbruelhart">edouardbruelhart</a>.

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: ["manexp_web_lists"]
        import:
        - https://raw.githubusercontent.com/pyapp-kit/griffe-fieldz/main/README.md
        options:
          show_signature: true
          show_source: false
          docstring_style: google
          docstring_section_style: table
          members_order: source
          separate_signature: true
          show_signature_annotations: true
          show_docstring_parameters: true
          show_docstring_returns: true
          show_docstring_description: true
          show_model_fields: false
          merge_init_into_class: true
          show_if_no_docstring: false
          show_members: true
          filters: ["!^_"]
          show_root_heading: false
          line_length: 60
          show_docstring_attributes: true
          show_docstring_examples: true
          extensions:
          - griffe_fieldz

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: deep orange
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: deep orange
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - content.tabs.link
  - content.code.annotate
  - content.code.copy
  - announce.dismiss
  - navigation.tabs
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.preview
  - navigation.instant.progress
  - navigation.path
  - navigation.sections
  - navigation.top
  - navigation.tracking
  - search.suggest
  - toc.follow
  icon:
    repo: fontawesome/brands/github

nav:
- Run: manexp_web_lists/run.md
- Core:
  - Json client: manexp_web_lists/core/json_client.md
  - Logging config: manexp_web_lists/core/logging_config.md
  - Mailer: manexp_web_lists/core/mailer.md
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/edouardbruelhart/Manexp-Web-Lists
  - icon: fontawesome/solid/globe
    link: https://manexp.ch

markdown_extensions:
- tables
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.snippets
