site_name: Manexp Web Lists Documentation
site_author: Edouard Brülhart

repo_name: edouardbruelhart/Manexp-Web-Lists
copyright: Maintained by <a
  href="https://github.com/edouardbruelhart">edouardbruelhart</a>.

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: ["manexp_web_lists"]
        import:
        - https://raw.githubusercontent.com/pyapp-kit/griffe-fieldz/main/README.md
        options:
          show_signature: true
          show_source: false
          docstring_style: google
          docstring_section_style: table
          members_order: source
          separate_signature: true
          show_signature_annotations: true
          show_docstring_parameters: true
          show_docstring_returns: true
          show_docstring_description: true
          show_model_fields: false
          merge_init_into_class: true
          show_if_no_docstring: false
          show_members: true
          filters: ["!^_"]
          show_root_heading: false
          line_length: 60
          show_docstring_attributes: true
          show_docstring_examples: true
          extensions:
          - griffe_fieldz

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: deep orange
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: deep orange
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - content.tabs.link
  - content.code.annotate
  - content.code.copy
  - announce.dismiss
  - navigation.tabs
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.preview
  - navigation.instant.progress
  - navigation.path
  - navigation.sections
  - navigation.top
  - navigation.tracking
  - search.suggest
  - toc.follow
  icon:
    repo: fontawesome/brands/github

nav:
- Run: manexp_web_lists/run.md
- Clients:
  - Gbif client: manexp_web_lists/clients/gbif_client.md
  - Translation client: manexp_web_lists/clients/translation_client.md
- Core:
  - Logging config: manexp_web_lists/core/logging_config.md
  - Mailer: manexp_web_lists/core/mailer.md
  - Parsers: manexp_web_lists/core/parsers.md
  - Strict model: manexp_web_lists/core/strict_model.md
- Exceptions:
  - Code mismatch: manexp_web_lists/exceptions/code_mismatch.md
  - Invalid chemical: manexp_web_lists/exceptions/invalid_chemical.md
  - Invalid environment: manexp_web_lists/exceptions/invalid_environment.md
  - Invalid pseudo boolean:
      manexp_web_lists/exceptions/invalid_pseudo_boolean.md
  - Invalid xml: manexp_web_lists/exceptions/invalid_xml.md
  - Language installation failed:
      manexp_web_lists/exceptions/language_installation_failed.md
  - Postgresql configuration failed:
      manexp_web_lists/exceptions/postgresql_configuration_failed.md
  - Separator error: manexp_web_lists/exceptions/separator_error.md
  - Unexpected xml child: manexp_web_lists/exceptions/unexpected_xml_child.md
  - Unexpected xml element:
      manexp_web_lists/exceptions/unexpected_xml_element.md
  - Unexpected xml language:
      manexp_web_lists/exceptions/unexpected_xml_language.md
  - Unresolved foreign key:
      manexp_web_lists/exceptions/unresolved_foreign_key.md
  - Unsupported os: manexp_web_lists/exceptions/unsupported_os.md
  - Unsupported type: manexp_web_lists/exceptions/unsupported_type.md
- Phytosanitary products:
  - Get phytosanitary products:
      manexp_web_lists/phytosanitary_products/get_phytosanitary_products.md
  - Extract:
    - Download phytosanitary products:
        manexp_web_lists/phytosanitary_products/extract/download_phytosanitary_products.md
    - Extract indications:
        manexp_web_lists/phytosanitary_products/extract/extract_indications.md
  - Load:
    - Load phytosanitary products:
        manexp_web_lists/phytosanitary_products/load/load_phytosanitary_products.md
  - Transform:
    - Clean indications:
        manexp_web_lists/phytosanitary_products/transform/clean_indications.md
    - Clean metadata:
        manexp_web_lists/phytosanitary_products/transform/clean_metadata.md
    - Clean products:
        manexp_web_lists/phytosanitary_products/transform/clean_products.md
    - Merge phyto:
        manexp_web_lists/phytosanitary_products/transform/merge_phyto.md
    - Parsers: manexp_web_lists/phytosanitary_products/transform/parsers.md
- Postgresql:
  - Apply schema: manexp_web_lists/postgresql/apply_schema.md
  - Configure database: manexp_web_lists/postgresql/configure_database.md
  - Database url: manexp_web_lists/postgresql/database_url.md
  - Generate create tables:
      manexp_web_lists/postgresql/generate_create_tables.md
  - Generate foreign key constraints:
      manexp_web_lists/postgresql/generate_foreign_key_constraints.md
  - Generate schema: manexp_web_lists/postgresql/generate_schema.md
  - Synchronize: manexp_web_lists/postgresql/synchronize.md
- Seeds:
  - Get seeds: manexp_web_lists/seeds/get_seeds.md
  - Extract:
    - Create countries: manexp_web_lists/seeds/extract/create_countries.md
    - Create register subtypes:
        manexp_web_lists/seeds/extract/create_register_subtypes.md
    - Create register types:
        manexp_web_lists/seeds/extract/create_register_types.md
    - Download plant varieties:
        manexp_web_lists/seeds/extract/download_plant_varieties.md
    - Download taxonomy: manexp_web_lists/seeds/extract/download_taxonomy.md
  - Load:
    - Load seeds: manexp_web_lists/seeds/load/load_seeds.md
  - Transform:
    - Booleanize plant varieties:
        manexp_web_lists/seeds/transform/booleanize_plant_varieties.md
    - Clean plant varieties denominations:
        manexp_web_lists/seeds/transform/clean_plant_varieties_denominations.md
    - Clean taxonomy: manexp_web_lists/seeds/transform/clean_taxonomy.md
    - Color taxonomy: manexp_web_lists/seeds/transform/color_taxonomy.md
    - Filter plant varieties:
        manexp_web_lists/seeds/transform/filter_plant_varieties.md
    - Filter taxonomy: manexp_web_lists/seeds/transform/filter_taxonomy.md
    - Iconize taxonomy: manexp_web_lists/seeds/transform/iconize_taxonomy.md
    - Merge taxonomy: manexp_web_lists/seeds/transform/merge_taxonomy.md
    - Replace plant varieties relations:
        manexp_web_lists/seeds/transform/replace_plant_varieties_relations.md
    - Translate countries:
        manexp_web_lists/seeds/transform/translate_countries.md
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/edouardbruelhart/Manexp-Web-Lists
  - icon: fontawesome/solid/globe
    link: https://manexp.ch

markdown_extensions:
- tables
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.snippets
