site_name: Manexp Web Lists Documentation
site_author: Edouard Brülhart

repo_name: edouardbruelhart/Manexp-Web-Lists
copyright: Maintained by <a
  href="https://github.com/edouardbruelhart">edouardbruelhart</a>.

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: ["manexp_web_lists"]
        import:
        - https://raw.githubusercontent.com/pyapp-kit/griffe-fieldz/main/README.md
        options:
          show_signature: true
          show_source: false
          docstring_style: google
          docstring_section_style: table
          members_order: source
          separate_signature: true
          show_signature_annotations: true
          show_docstring_parameters: true
          show_docstring_returns: true
          show_docstring_description: true
          show_model_fields: false
          merge_init_into_class: true
          show_if_no_docstring: false
          show_members: true
          filters: ["!^_"]
          show_root_heading: false
          line_length: 60
          show_docstring_attributes: true
          show_docstring_examples: true
          extensions:
          - griffe_fieldz

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: deep orange
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: deep orange
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - content.tabs.link
  - content.code.annotate
  - content.code.copy
  - announce.dismiss
  - navigation.tabs
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.preview
  - navigation.instant.progress
  - navigation.path
  - navigation.sections
  - navigation.top
  - navigation.tracking
  - search.suggest
  - toc.follow
  icon:
    repo: fontawesome/brands/github

nav:
- Run: manexp_web_lists/run.md
- Core:
  - Logging config: manexp_web_lists/core/logging_config.md
  - Mailer: manexp_web_lists/core/mailer.md
  - Strict model: manexp_web_lists/core/strict_model.md
- Countries:
  - Get countries: manexp_web_lists/countries/get_countries.md
  - Extract:
    - Download countries:
        manexp_web_lists/countries/extract/download_countries.md
  - Transform:
    - Translate countries:
        manexp_web_lists/countries/transform/translate_countries.md
- Exceptions:
  - Invalid chemical: manexp_web_lists/exceptions/invalid_chemical.md
  - Invalid pseudo boolean:
      manexp_web_lists/exceptions/invalid_pseudo_boolean.md
  - Invalid xml: manexp_web_lists/exceptions/invalid_xml.md
  - Separator error: manexp_web_lists/exceptions/separator_error.md
- Phytosanitary products:
  - Get phytosanitary products:
      manexp_web_lists/phytosanitary_products/get_phytosanitary_products.md
  - Extract:
    - Download phytosanitary products:
        manexp_web_lists/phytosanitary_products/extract/download_phytosanitary_products.md
- Register subtypes:
  - Get register subtypes:
      manexp_web_lists/register_subtypes/get_register_subtypes.md
  - Create:
    - Create register subtypes:
        manexp_web_lists/register_subtypes/create/create_register_subtypes.md
- Register types:
  - Get register types: manexp_web_lists/register_types/get_register_types.md
  - Create:
    - Create register types:
        manexp_web_lists/register_types/create/create_register_types.md
- Seeds:
  - Get seeds: manexp_web_lists/seeds/get_seeds.md
  - Extract:
    - Download seeds: manexp_web_lists/seeds/extract/download_seeds.md
  - Transform:
    - Clean booleans: manexp_web_lists/seeds/transform/clean_booleans.md
    - Clean denominations:
        manexp_web_lists/seeds/transform/clean_denominations.md
    - Filter columns: manexp_web_lists/seeds/transform/filter_columns.md
    - Remove unnecessary seeds:
        manexp_web_lists/seeds/transform/remove_unnecessary_seeds.md
    - Rename columns: manexp_web_lists/seeds/transform/rename_columns.md
- Taxonomy:
  - Get taxonomy: manexp_web_lists/taxonomy/get_taxonomy.md
  - Clients:
    - Gbif client: manexp_web_lists/taxonomy/clients/gbif_client.md
  - Extract:
    - Download taxonomy: manexp_web_lists/taxonomy/extract/download_taxonomy.md
  - Models:
    - Taxon rank: manexp_web_lists/taxonomy/models/taxon_rank.md
  - Transform:
    - Clean taxonomy: manexp_web_lists/taxonomy/transform/clean_taxonomy.md
    - Color taxonomy: manexp_web_lists/taxonomy/transform/color_taxonomy.md
    - Filter columns: manexp_web_lists/taxonomy/transform/filter_columns.md
    - Filter rows: manexp_web_lists/taxonomy/transform/filter_rows.md
    - Iconize taxonomy: manexp_web_lists/taxonomy/transform/iconize_taxonomy.md
    - Merge taxonomy: manexp_web_lists/taxonomy/transform/merge_taxonomy.md
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/edouardbruelhart/Manexp-Web-Lists
  - icon: fontawesome/solid/globe
    link: https://manexp.ch

markdown_extensions:
- tables
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.highlight:
    pygments_lang_class: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.snippets
