from polars import DataFrame

COLUMNS_TO_DROP = [
    "National ID",
    "Breeder's Reference",
    "Maintainer N°",
    "Application Date",
    "Publication Date of Application",
    "Publication Date of Registration",
    "Publication Date of Denomination",
    "Renewal Date",
    "End Date",
    "Market Extension Date",
    "Foreseeable Expiration Date",
    "Variety Description (DUS)",
    "Variety Description (VCU)",
    "Description",
    "Pre-Marketing Authorization (PMA)",
    "PMA Info",
    "Region of Origin",
    "Component Variety",
    "Amateur Variety",
    "Seed Category",
    "Propagation Mode",
    "Rootstock",
    "Rootstock Info",
    "Name of the Breeder(s)",
    "Name of the Applicant(s)",
    "Registration Date",
    "Conservation Variety",
    "Other Partie's Name",
    "Title Holder",
    "Proposal Date of Denomination",
    "Approval Date of Denomination",
    "Organic Info",
    "Apomictic Uniclonal",
    "Fescue Type",
    "Fodder Use",
    "Germity",
    "Glucosinolate and Erucic Acid Content",
    "Hemp Type",
    "Hordeum Type",
    "Linum Type",
    "Lupin Type",
    "Maize Use",
    "No VCU",
    "Oil and Fiber Use",
    "Ploidy",
    "Pollinator",
    "Season Type",
    "Sorghum Type",
    "Synthetic",
    "THC Content",
    "True Potato Seed Variety",
    "Varietal Association",
    "Bean Type",
    "Broccoli Type",
    "Cheltenham Beet",
    "Cucumis Type",
    "Cucurbita Type",
    "Cynara Type",
    "Echalion",
    "Endive Type",
    "Fodder Carrot",
    "Lettuce Type",
    "Parsley Type",
    "Pepper Type",
    "Pisum Type",
    "Agri Pea Type",
    "Chromosomata",
    "FAO Maturity",
    "Fibre Length",
    "Hybrid Type",
    "Ploidy of Components",
    "Pollination Type",
    "Alium Type",
    "Black Radish Type",
    "Tomato Type",
    "Veg Pea Type",
    "General Remarks",
    "MS Action",
    "Catalogue Name",
    "OJ Publication Date",
    "EUPVP Publication Date",
    "Variety ID",
    "Denomination Status",
    "EU Variety Status",
    "Is Conventional Denomination",
    "EU Denom Status",
]


def filter_columns(seeds: DataFrame) -> DataFrame:
    """
    Remove unwanted fields from the official european seeds list.

    Args:
        seeds: The seeds list in polars dataframe

    Returns:
        DataFrame: The filtered seeds list
    """
    filtered_seeds = seeds.drop(COLUMNS_TO_DROP)

    return filtered_seeds
