class PostgresqlConfigurationFailedError(Exception):
    """
    Raised when the PostgreSQL automatic configuration package can't be made.

    Args:
            exit_code: The exit code generated by the configuration error
    """

    def __init__(self, exit_code: int):
        self.exit_code = exit_code

        message = f"PostgreSQL configuration failed with exit code {self.exit_code}"
        super().__init__(message)
